//{{NO_DEPENDENCIES}}
// fichier Include Microsoft Visual C++.
// Utilisé par NZArchive.rc
//
#define IDC_MYICON                      2
#define IDC_YFC_B_PICK                  3
#define IDD_NZAGUI_DIALOG               102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_NZAGUI                      107
#define IDI_SMALL                       108
#define IDC_NZAGUI                      109
#define IDR_MAINFRAME                   128
#define IDD_PWDBOX                      129
#define IDD_ARCHIVE_INFORMATION         130
#define IDI_Icon_x64                    133
#define IDD_TestArchive                 135
#define IDD_ExtractArchive              136
#define IDD_DeleteFromArchive           137
#define IDD_CreateArchive               138
#define IDR_MENU1                       139
#define IDD_FastOpen1                   139
#define IDD_LANGUAGE                    140
#define IDD_ADD_FILE                    141
#define IDI_ABOUT                       144
#define IDI_ADD                         145
#define IDI_ARCINFO                     146
#define IDI_CREATE                      147
#define IDI_DELETE                      148
#define IDI_EXTRACTALL                  149
#define IDI_EXTRACTSEL                  150
#define IDI_FILTER                      151
#define IDI_LANG                        152
#define IDI_OPEN                        153
#define IDI_TEST                        154
#define IDD_CheckTable                  157
#define IDR_ZSTDFILE1                   158
#define IDR_ZSTDRobotoCondensedRegularTTF 158
#define IDI_NBOX                        159
#define IDD_YesFolderCancel             160
#define ID_PWD_TEXTBOX                  1000
#define ID_PWD_OK                       1001
#define ID_PWD_CANCEL                   1002
#define IDC_ADD_SOURCE                  1003
#define IDC_CREATE_PASSWORD             1004
#define IDC_EDIT3                       1005
#define IDC_AINFO_FILES                 1006
#define ID_ARC_INF_CLOSE                1007
#define IDC_TEST_FileName               1008
#define ID_TEST_Close                   1009
#define ID_TEST_Cancel                  1010
#define IDC_EDIT4                       1011
#define IDC_TEST_TXTRESULT              1012
#define IDC_TEST_PROGRESS               1013
#define IDC_TEST_lblAvancement          1014
#define IDC_EXTR_FileName               1015
#define IDC_EXTR_PROGRESS               1016
#define IDC_EXTR_lblAvancement          1017
#define IDC_EXTR_TXTRESULT              1018
#define ID_EXTR_Close                   1019
#define ID_EXTR_Cancel                  1020
#define IDC_EXTR_PROGRESS_FILE          1021
#define IDC_EXTR_lblAvancementFile      1022
#define CREATE_LBL_COMP2                1023
#define IDC_CREATE_BTN_BrowseDest       1024
#define IDC_CREATE_BTN_BrowseSource     1025
#define IDC_CREATE_Slider               1026
#define IDC_CREATE_Progress             1027
#define IDC_CREATE_File_being_compressed 1028
#define IDC_CREATE_Progression_byte     1029
#define IDC_CREATE_BTN_CANCELOP         1030
#define IDC_CREATE_BTN_CLOSE            1031
#define IDC_CREATE_BTN_Start            1032
#define IDC_CREATE_LBL_LEVEL            1033
#define CREATE_LBL_REDUNDANCY2          1033
#define IDC_DELETE_PROGRESS             1034
#define IDC_CREATE_SliderREDUNDANCY     1034
#define IDC_DELETE_lblAvancementFile    1035
#define CREATE_LBL_NBTHREAD1            1035
#define LBL_AI_ARCHIVENAME              1036
#define CREATE_LBL_NBTHREAD2            1036
#define LBL_AI_ARCHIVEVERSION           1037
#define LBL_AI_ARCHIVESIZE              1038
#define IDC_CREATE_SliderThread         1038
#define LBL_AI_ARCHIVEFILES             1039
#define CREATE_LBL_NZALOC               1040
#define CREATE_LBL_COMP1                1041
#define CREATE_LBL_ENC1                 1042
#define CREATE_LBL_ENC2                 1043
#define CREATE_LBL_SOURCE               1044
#define CREATE_LBL_COMPPROG             1045
#define CREATE_LBL_FILE                 1046
#define CREATE_LBL_PROGRESS             1047
#define IDC_LBL_PWD                     1048
#define CREATE_LBL_ENC3                 1048
#define IDC_TEST_LBLFILE                1049
#define CREATE_LBL_REDUNDANCY1          1049
#define IDC_TEST_LBLPOSITION            1050
#define IDC_LANG_LIST                   1051
#define IDC_LANG_CHANGE                 1052
#define IDC_LANG_CANCEL                 1053
#define IDC_PROGRESS_FASTEXTRACT        1054
#define IDC_EXTRACT_FILE1               1054
#define IDC_FASTEXTR_lblAvancementFile  1055
#define IDC_EXTRACT_FILE2               1055
#define IDC_AINFO_NAME                  1056
#define IDC_EXTRACT_FILEWRITTEN         1056
#define IDC_CREATE_EDIT_Dest            1057
#define IDC_EXTRACT_DATAWRITTEN         1057
#define IDC_EDIT2                       1058
#define IDC_EXTRACT_TOTAL               1058
#define IDC_AINFO_VERSION               1059
#define ID_ADDSTART                     1059
#define IDC_AINFO_SIZE                  1060
#define IDC_ADD_DROPLIST                1060
#define IDC_CREATE_Edit_SourceFolder    1061
#define ID_ADD_CLOSE                    1061
#define IDC_ADD_BROWSE                  1062
#define IDC_CREATE_DROPLIST_CPU         1062
#define IDC_RADIOFILE                   1063
#define IDC_RADIOFOLDER                 1064
#define IDC_STATIC_ADD                  1065
#define IDC_STATIC_INSERTPOINT          1066
#define IDC_ADD_PROGRESS                1067
#define IDC_STATIC_PROGRESSION          1068
#define IDC_STATIC_AVANCEMENT           1069
#define ID_ADD_CANCEL2                  1070
#define IDC_ADD_SLIDER                  1071
#define IDC_ADD_LBL_LEVEL2              1072
#define IDC_ADD_LBL_LEVEL1              1073
#define IDC_STATIC_AVANCEMENT2          1074
#define IDC_CREATE_RADIOCHACHA          1075
#define ADD_LBL_NBTHREAD1               1075
#define LBLCREATE_LBL_THREAD1           1075
#define IDC_CREATE_RADIOAES256          1076
#define IDC_ADD_SLIDERTHR               1076
#define IDC_CREATE_RADIONONE            1077
#define ADD_LBL_NBTHREAD2               1077
#define IDC_CREATE_ListInfo             1078
#define IDC_ADD_DROPLIST_CPU2           1078
#define EXTRACT_LISTBOX                 1079
#define IDC_ADD_LISTBOX                 1080
#define TEST_LBOX                       1081
#define IDC_AI_RESUME                   1082
#define IDC_INTEGRITY_PROGRESS          1086
#define IDC_INTEGRITY_LISTBOX           1087
#define IDC_AI_ListInfo                 1088
#define IDC_CREATE_DROPLIST_LEVELCOMP   1092
#define IDC_ABOUT0                      1093
#define IDC_ABOUT1                      1094
#define IDC_ABOUT2                      1095
#define IDC_ABOUT3                      1096
#define IDC_ADD_DROPLIST_LEVELCOMP      1097
#define IDC_YFC_EDIT                    1098
#define IDC_YFC_B_OK                    1099
#define IDC_YFC_B_CANCEL                1100
#define ID_FILE_OPENARCHIVE             32771
#define ID_FILE_ARCHIVEINFORMATION      32772
#define ID_FILE_CREATEARCHIVE           32773
#define ID_TOOL_TEST                    32774
#define ID_EXTRACTION_EXTRACTSELECTIONTO 32775
#define ID_EDIT_SELECTALL               32776
#define ID_EDIT_SELECTNONE              32777
#define ID_EDIT_INVERTSELECTION         32778
#define ID_TOOL_VIEWSELECTEDFILEINHEXA  32779
#define ID_EXTRACTION_UNCOMPRESSANDOPENTHEFILE 32780
#define ID_EXTRACTION_OPENTHEFILEALONE  32781
#define ID_EXTRACTION_EXTRACTALLFILESTO 32782
#define ID_PREFERENCE_ASSOCIATENZAFILEWITHNZARCHIVE 32796
#define ID_PREFERENCE_ADDNZA            32797
#define ID_PREFERENCE_ADDNZAEXPLORER    32798
#define ID_MENU_DELETE                  32799
#define ID_MENU_OPEN                    32800
#define ID_CONTEXT_OPEN                 32801
#define ID_CONTEXT_DELETE               32802
#define ID_LANGUAGE_ENGLISH             32803
#define ID_LANGUAGE                     32804
#define ID_LANGUAGE_SELECTOR            32805
#define ID_ACTION_ADDAFILE              32806
#define ID_ACTION_ADDADIRECTORY         32807
#define ID_ACTION_DELETESELECTION       32808
#define ID_LANGUAGE_CHANGE              32809
#define ID_MENU_ADD                     32810
#define ID_CONTEXT_ADD                  32811
#define ID_MENU_OPENWITH                32812
#define ID_CONTEXT_OPENWITH             32813
#define ID_HELP_ABOUT                   32820
#define ID_HELP_LANGUAGE                32821
#define ID_LANG                         32822
#define ID_ABOUT                        32823
#define ID_MENU_EXTRACTTOWINDOWSEXPLORER 32829
#define ID_EXTRACTTOWINDOWSEXPLORER_ACTIVEWINDOWS 32830
#define ID_SETTINGS_ASSOCIATENZARCHIVEWITHNZAFILES 32831
#define ID_SETTINGS_REMOVENZAASSOCIATION 32832
#define IDC_STATIC                      -1
#define IDC_YFC_LABEL                   -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        161
#define _APS_NEXT_COMMAND_VALUE         32833
#define _APS_NEXT_CONTROL_VALUE         1101
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
